// @vitest-environment node
import { beforeAll, describe, expect, it } from "vitest";
import { createTestDb, errorOf, type TestDb } from "./harness";

let t: TestDb;
let admin: { id: string };

beforeAll(async () => {
  t = await createTestDb();
  admin = await t.createUser({ role: "superadmin" });
}, 60_000);

interface Code {
  code: string;
  plan_id: string;
  uses_limit: number | null;
  expires_at: string | null;
}

const createCodes = async (
  plan: string,
  quantity = 1,
  uses: number | null = 1,
  days: number | null = 30,
) =>
  t.as<Code>(admin.id, "select * from admin_create_plan_codes($1, $2, $3, $4, 'teste')", [
    plan,
    quantity,
    uses,
    days,
  ]);
const validate = async (userId: string, code: string) =>
  (await t.as<{ ok: boolean }>(userId, "select validate_plan_code($1) as ok", [code]))[0].ok;
const redeem = async (userId: string, code: string) =>
  (
    await t.as<{
      r: { ok: boolean; plan_id?: string; period_end?: string; rate_limited?: boolean };
    }>(userId, "select redeem_plan_code($1) as r", [code])
  )[0].r;
const planOf = async (userId: string) =>
  (await t.admin<{ id: string }>("select (effective_plan($1)).id", [userId]))[0].id;

describe("receiver data", () => {
  it("comes filled with the owner's PIX, bank and WhatsApp", async () => {
    const user = await t.createUser();
    const [row] = await t.as<Record<string, string>>(
      user.id,
      "select pix_key, receiver_name, bank_name, whatsapp from billing_settings",
    );
    expect(row).toEqual({
      pix_key: "b26ee480-c458-4a1c-8d5c-229087cf62ca",
      receiver_name: "Gabriel Nunes",
      bank_name: "Mercado Pago",
      whatsapp: "5571999428340",
    });
  });

  it("shows members only the public fields", async () => {
    const user = await t.createUser();
    expect(await errorOf(t.as(user.id, "select updated_by from billing_settings"))).toMatch(
      /permission denied/,
    );
    expect(await errorOf(t.as(user.id, "select * from billing_settings"))).toMatch(
      /permission denied/,
    );
  });

  it("lets only admins change it, and checks the WhatsApp format", async () => {
    const user = await t.createUser();
    await t.as(user.id, "update billing_settings set bank_name = 'Hacker' where id");
    const [row] = await t.admin<{ bank_name: string }>("select bank_name from billing_settings");
    expect(row.bank_name).toBe("Mercado Pago");

    expect(
      await errorOf(t.as(admin.id, "update billing_settings set whatsapp = '(71) 9999' where id")),
    ).toMatch(/check constraint/);
  });
});

describe("plan codes", () => {
  it("are generated by admins only, with a plan prefix and no ambiguous characters", async () => {
    const codes = await createCodes("plus_semester", 3);
    expect(codes).toHaveLength(3);
    for (const c of codes) expect(c.code).toMatch(/^SEM-[A-HJ-NP-Z2-9]{8}$/);
    expect(new Set(codes.map((c) => c.code)).size).toBe(3);
    expect((await createCodes("pro"))[0].code).toMatch(/^PRO-/);
    expect((await createCodes("plus"))[0].code).toMatch(/^EST-/);

    const user = await t.createUser();
    expect(
      await errorOf(t.as(user.id, "select * from admin_create_plan_codes('pro', 1, 1, 30, null)")),
    ).toBe("ACCESS_DENIED");
    expect(await errorOf(createCodes("free"))).toBe("PLAN_NOT_AVAILABLE");
  });

  it("can never be read by members", async () => {
    await createCodes("pro");
    const user = await t.createUser();
    expect(await t.as(user.id, "select * from plan_codes")).toHaveLength(0);
    expect(await t.as(user.id, "select * from plan_code_redemptions")).toHaveLength(0);
    expect(await errorOf(t.as(user.id, "select * from admin_list_plan_codes(10)"))).toBe(
      "ACCESS_DENIED",
    );
  });

  it("release the plan once, ignoring case and spaces", async () => {
    const [{ code }] = await createCodes("plus_semester");
    const user = await t.createUser();
    expect(await validate(user.id, `  ${code.toLowerCase()} `)).toBe(true);

    const result = await redeem(user.id, code.toLowerCase());
    expect(result.ok).toBe(true);
    expect(result.plan_id).toBe("plus_semester");
    expect(await planOf(user.id)).toBe("plus_semester");

    // Single use: tied to this account now.
    const other = await t.createUser();
    expect(await validate(other.id, code)).toBe(false);
    expect(await redeem(other.id, code)).toEqual({ ok: false });
    // And the same account can't stack it twice.
    expect(await redeem(user.id, code)).toEqual({ ok: false });
  });

  it("answer only false for unknown, expired, revoked or used-up codes", async () => {
    const user = await t.createUser();
    const [expired] = await createCodes("pro");
    await t.admin(
      "update plan_codes set expires_at = now() - interval '1 minute' where code = $1",
      [expired.code],
    );
    const [revoked] = await createCodes("pro");
    await t.as(admin.id, "select admin_revoke_plan_code($1)", [revoked.code]);
    const [usedUp] = await createCodes("pro");
    await redeem((await t.createUser()).id, usedUp.code);

    for (const code of ["PRO-NAOEXISTE", expired.code, revoked.code, usedUp.code, ""]) {
      const someone = await t.createUser();
      expect(await validate(someone.id, code), code).toBe(false);
      expect(await redeem(someone.id, code), code).toEqual({ ok: false });
      expect(await planOf(someone.id)).toBe("free");
    }
    expect(await planOf(user.id)).toBe("free");
  });

  it("stop at the use limit, one use per account", async () => {
    const [{ code }] = await createCodes("plus", 1, 2, null);
    const results = [];
    for (let i = 0; i < 3; i++) results.push((await redeem((await t.createUser()).id, code)).ok);
    expect(results).toEqual([true, true, false]);
    const [row] = await t.admin<{ uses_count: number }>(
      "select uses_count from plan_codes where code = $1",
      [code],
    );
    expect(row.uses_count).toBe(2);
  });

  it("slow down guessing: after 8 wrong tries even a good code answers false for an hour", async () => {
    const user = await t.createUser();
    for (let i = 0; i < 8; i++) await redeem(user.id, `PRO-ERRADO${i}`);
    const [{ code }] = await createCodes("pro");
    expect(await validate(user.id, code)).toBe(false);
    expect(await redeem(user.id, code)).toEqual({ ok: false, rate_limited: true });

    await t.admin(
      "update plan_code_attempts set attempted_at = now() - interval '2 hours' where user_id = $1",
      [user.id],
    );
    expect((await redeem(user.id, code)).ok).toBe(true);
  });

  it("keep the days already paid and settle an open order for the same plan", async () => {
    const user = await t.createUser();
    const [order] = await t.as<{ id: string }>(user.id, "select * from create_pix_request('plus')");
    const first = await t.as<{ period_end: string }>(
      admin.id,
      "select * from admin_confirm_pix($1, 'ok')",
      [order.id],
    );
    const [pending] = await t.as<{ id: string }>(
      user.id,
      "select * from create_pix_request('plus_semester')",
    );

    const [{ code }] = await createCodes("plus_semester");
    const result = await redeem(user.id, code);
    expect(new Date(result.period_end!).getTime() - new Date(first[0].period_end).getTime()).toBe(
      183 * 86_400_000,
    );
    const [settled] = await t.admin<{ status: string; admin_note: string }>(
      "select status, admin_note from payment_requests where id = $1",
      [pending.id],
    );
    expect(settled).toEqual({ status: "confirmed", admin_note: `Liberado pelo código ${code}` });
  });

  it("list who used each code for the admin", async () => {
    const [{ code }] = await createCodes("pro");
    const user = await t.createUser();
    await redeem(user.id, code);
    const rows = await t.as<{ code: string; uses_count: number; used_by: string | null }>(
      admin.id,
      "select code, uses_count, used_by from admin_list_plan_codes(500) where code = $1",
      [code],
    );
    expect(rows[0].uses_count).toBe(1);
    expect(rows[0].used_by).toBeTruthy();
  });
});
